# Uri-challenge-python
Some Uri problem solved with Python 3.6 :)

In 2021 I'm committed to solve at least one challenge per day.
